---
title: "RHadoop"
author: "Veerasak Kritsanapraphan"
date: "3/24/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Hadoop

```{r}
# Hadoop with R
# Install neccessary packages
#install.packages( c('rJava','RJSONIO', 'itertools', #'digest','Rcpp','httr','functional','devtools', 'plyr','reshape2'))


Sys.setenv("HADOOP_CMD"="/usr/local/Cellar/hadoop/2.7.3/bin/hadoop")
Sys.setenv("HADOOP_STREAMING"="/usr/local/Cellar/hadoop/2.7.3/libexec/share/hadoop/tools/lib/hadoop-streaming-2.7.2.jar")
Sys.getenv("HADOOP_CMD")
Sys.setenv("HADOOP_HOME"="/usr/local/Cellar/hadoop/2.7.3")
Sys.setenv("RSCRIPT"="/usr/local/bin/Rscript")
```

```{r}
library(rmr2)
library(rhdfs)
gdp <- NA
gdp <- read.csv("GDP.csv")
gdp <- gdp[,1:4]
```

```{r}
gdp$GDP <- as.double(gsub(",","",gdp$GDP))
head(gdp)

hdfs.init()
gdp.values <- to.dfs(gdp)

aaplRevenue = 181890

gdp.map.fn <- function(k,v) {
    key <- ifelse(v[4] < aaplRevenue, "less", "greater")
    keyval(key, 1)
}

count.reduce.fn <- function(k,v) {
    keyval(k, length(v))
}

count <- mapreduce(input=gdp.values, map = gdp.map.fn, reduce = count.reduce.fn)

from.dfs(count)
```

