---
title: "Stepwise Logistic Regression"
author: "Veerasak Kritsanapraphan"
date: "8/3/2017"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Stepwise Logistic Regression

Import packages necessary first.

```{r}
library(MASS)
library(plyr)
library(ggplot2)
library(knitr)
```

Prepare data

```{r}
# Assign better variable names
colnames(birthwt) <- c("birthwt.below.2500", "mother.age", "mother.weight", 
    "race", "mother.smokes", "previous.prem.labor", "hypertension", "uterine.irr", 
    "physician.visits", "birthwt.grams")

# Assign better labels to categorical variables
birthwt <- transform(birthwt, 
            race = as.factor(mapvalues(race, c(1, 2, 3), 
                              c("white","black", "other"))),
            mother.smokes = as.factor(mapvalues(mother.smokes, 
                              c(0,1), c("no", "yes"))),
            hypertension = as.factor(mapvalues(hypertension, 
                              c(0,1), c("no", "yes"))),
            uterine.irr = as.factor(mapvalues(uterine.irr, 
                              c(0,1), c("no", "yes"))),
            birthwt.below.2500 = as.factor(mapvalues(birthwt.below.2500,
                              c(0,1), c("no", "yes")))
            )

```

Run logistic regression

```{r}
formula = birthwt.below.2500 ~ mother.age + mother.weight + physician.visits + mother.smokes + uterine.irr + previous.prem.labor + hypertension
fullmod = glm(formula, family = binomial, data = birthwt)
summary(fullmod)
```

No independent variables

```{r}
nothing <- glm(birthwt.below.2500 ~ 1,family=binomial, data = birthwt)
summary(nothing)
```

Stepwise Logistic Regression ("Backward")
```{r}
backwards = step(fullmod) # Backwards selection is the default
formula(backwards)
summary(backwards) 
```

Stepwise Logistic Regression ("Forward")
```{r}
forwards <- step(fullmod, direction="forward")
formula(forwards)
summary(forwards)
```


